<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/pe/EngineTypes" xmlns:pfx="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:ns2="http://schemas.tibco.com/bw/plugins/jdbc/5.0/jdbcExceptions" xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns1="http://www.tibco.com/pe/DeployedVarsType" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx5="http://www.tibco.com/CommonLE2/Public/Common/Dummy" xmlns:tib="http://www.tibco.com/bw/xslt/custom-functions" xmlns:pfx4="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Configuration/Category" xmlns:pfx3="http://www.tibco.com/CommonLE/namespace/Custom" xmlns:pfx2="http://xmlns.example.com/unique/default/namespace/1098735544074" xmlns:pfx7="http://www.tibco.com/CommonLE2/Private/Administration" xmlns:pfx6="http://www.tibco.com/CommonLE2/namespace/private/Common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xsd:import namespace="http://www.tibco.com/CommonLE/namespace/Custom" schemaLocation="/Shared Resources/Schema Definitions/Custom/ExceptionCategory.xsd"/>
    <xsd:import namespace="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Configuration/Category" schemaLocation="/SharedResources/SchemaDefinitions/Public/Pluggable/GUI/Administration/Configuration/ExceptionCategory.xsd"/>
    <xsd:import namespace="http://www.tibco.com/CommonLE2/namespace/private/Common" schemaLocation="/SharedResources/SchemaDefinitions/Private/Common/LocalExceptions.xsd"/>
    <xsd:import namespace="http://www.tibco.com/CommonLE2/Private/Administration" schemaLocation="/SharedResources/SchemaDefinitions/Private/Administration/QueryUpdate.xsd"/>
    <xsd:import namespace="http://www.tibco.com/CommonLE2/Public/Common/Dummy" schemaLocation="/SharedResources/SchemaDefinitions/Public/Pluggable/GUI/Common/DummyReturnMessage.xsd"/>
    <pd:name>Administration/DataAccess/Category/Oracle/CreateCategory.process</pd:name>
    <pd:description>Creates a new exception category</pd:description>
    <pd:startName>Start</pd:startName>
    <pd:startType ref="pfx7:CategoryUpdate"/>
    <pd:startX>52</pd:startX>
    <pd:startY>84</pd:startY>
    <pd:returnBindings>
        <pfx5:Dummy>
            <pfx5:StatusMessage>
                <xsl:value-of select="$_globalVariables/ns1:GlobalVariables/ReservedIDs/DummyID"/>
            </pfx5:StatusMessage>
        </pfx5:Dummy>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endX>396</pd:endX>
    <pd:endY>85</pd:endY>
    <pd:errorSchemas>
        <Schema1 ref="pfx6:ApplicationIDNotFound"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1284485316818</pd:targetNamespace>
    <pd:activity name="Insert Exception Category">
        <pd:type>com.tibco.plugin.jdbc.JDBCUpdateActivity</pd:type>
        <pd:resourceType>ae.activities.JDBCUpdateActivity</pd:resourceType>
        <pd:x>196</pd:x>
        <pd:y>91</pd:y>
        <config>
            <timeout>%%Database/MIG_Timeout%%</timeout>
            <commit>false</commit>
            <emptyStrAsNil>false</emptyStrAsNil>
            <jdbcSharedConfig>/SharedResources/Connections/Database/DBServerOracle.sharedjdbc</jdbcSharedConfig>
            <statement>Insert into exceptioncategory (ApplicationID, name, Description) 
Values (?, ?, ?)</statement>
            <Prepared_Param_DataType>
                <parameter>
                    <parameterName>ApplicationID</parameterName>
                    <dataType>VARCHAR</dataType>
                </parameter>
                <parameter>
                    <parameterName>CategoryName</parameterName>
                    <dataType>VARCHAR</dataType>
                </parameter>
                <parameter>
                    <parameterName>Description</parameterName>
                    <dataType>VARCHAR</dataType>
                </parameter>
            </Prepared_Param_DataType>
        </config>
        <pd:inputBindings>
            <jdbcUpdateActivityInput>
                <ApplicationID>
                    <xsl:value-of select="$Start/pfx7:CategoryUpdate/pfx7:ID"/>
                </ApplicationID>
                <CategoryName>
                    <xsl:value-of select="$Start/pfx7:CategoryUpdate/pfx7:Name"/>
                </CategoryName>
                <Description>
                    <xsl:value-of select="$Start/pfx7:CategoryUpdate/pfx7:Description"/>
                </Description>
            </jdbcUpdateActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="SQL Exception">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>108</pd:x>
        <pd:y>191</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=JDBCSQLException namespace=http://schemas.tibco.com/bw/plugins/jdbc/5.0/jdbcExceptions</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Generate Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>353</pd:x>
        <pd:y>192</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <pfx:ActivityInput>
                <message>
                    <xsl:value-of select="$_globalVariables/ns1:GlobalVariables/Exceptions/Common/Messages/ApplicationIDNotFound"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$_globalVariables/ns1:GlobalVariables/Exceptions/Common/Codes/ApplicationIDNotFound"/>
                </messageCode>
                <data>
                    <pfx6:ApplicationIDNotFound>
                        <pfx6:Message>
                            <xsl:value-of select="$_globalVariables/ns1:GlobalVariables/Exceptions/Common/Messages/ApplicationIDNotFound"/>
                        </pfx6:Message>
                        <pfx6:Code>
                            <xsl:value-of select="$_globalVariables/ns1:GlobalVariables/Exceptions/Common/Codes/ApplicationIDNotFound"/>
                        </pfx6:Code>
                    </pfx6:ApplicationIDNotFound>
                </data>
            </pfx:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Rethrow">
        <pd:type>com.tibco.pe.core.RethrowActivity</pd:type>
        <pd:resourceType>ae.activities.rethrow</pd:resourceType>
        <pd:x>110</pd:x>
        <pd:y>299</pd:y>
        <config/>
        <pd:inputBindings/>
    </pd:activity>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>Insert Exception Category</pd:to>
        <pd:lineType>Straight</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Insert Exception Category</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Straight</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>SQL Exception</pd:from>
        <pd:to>Generate Error</pd:to>
        <pd:xpathDescription>AppID does not exist</pd:xpathDescription>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>xpath</pd:conditionType>
        <pd:xpath>$SQL-Exception/ns2:JDBCSQLException/msgCode = $_globalVariables/ns1:GlobalVariables/Exceptions/DB/Codes/SQLIntegrityError and 
$SQL-Exception/ns2:JDBCSQLException/sqlState = $_globalVariables/ns1:GlobalVariables/Exceptions/DB/Codes/SQLIntegrityState</pd:xpath>
    </pd:transition>
    <pd:transition>
        <pd:from>SQL Exception</pd:from>
        <pd:to>Rethrow</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>otherwise</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>