<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/pe/EngineTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlPfx="http://www.tibco.com/CommonLE2/namespace/ExceptionManagement/GUIServices" xmlns:ns5="http://www.tibco.com/schemas/COMMONLENEW/SharedResources/SchemaDefinitions/Public/Pluggable/GUI/Common/ListQuery.xsd" xmlns:ns12="http://www.tibco.com/CommonLE/namespace/Common" xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns2="http://www.tibco.com/CommonLE2/namespace/Logging/GUIServices" xmlns:ns1="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:ns4="http://www.tibco.com/pe/DeployedVarsType" xmlns:ns3="http://www.tibco.com/CommonLE2/Public/Common" xmlns:pfx5="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/ExceptionManagement/ExceptionListQuery" xmlns:pfx4="http://www.tibco.com/CommonLE2/namespace/private/Common" xmlns:pfx6="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Exception/ExceptionList">
    <wsdl:import namespace="http://www.tibco.com/CommonLE2/namespace/ExceptionManagement/GUIServices" location="/SharedResources/WSDL/GUI/ExceptionManagement/intfResolveExceptions.wsdl"/>
    <pd:name>ExceptionManagement/GUIServices/wsRetrieveExceptionList.process</pd:name>
    <pd:startName>Start</pd:startName>
    <pd:startType wsMsgRef="wsdlPfx:ExceptionListQuery"/>
    <pd:startX>26</pd:startX>
    <pd:startY>55</pd:startY>
    <pd:returnBindings>
        <wsdlPfx:ExceptionList>
            <parameters>
                <xsl:choose>
                    <xsl:when test="count($Retrieve-Exception-List/pfx6:ExceptionList/pfx6:ExceptionRecord)>0">
                        <pfx6:ExceptionList>
                            <xsl:copy-of select="$Retrieve-Exception-List/pfx6:ExceptionList/pfx6:ExceptionRecord"/>
                        </pfx6:ExceptionList>
                    </xsl:when>
                    <xsl:otherwise>
                        <pfx6:ExceptionList/>
                    </xsl:otherwise>
                </xsl:choose>
            </parameters>
        </wsdlPfx:ExceptionList>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endType wsMsgRef="wsdlPfx:ExceptionList"/>
    <pd:endX>347</pd:endX>
    <pd:endY>55</pd:endY>
    <pd:errorSchemas>
        <Schema1 wsMsgRef="wsdlPfx:Error"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1284434511875</pd:targetNamespace>
    <pd:activity name="Retrieve Exception List">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>188</pd:x>
        <pd:y>63</pd:y>
        <config>
            <processName>/ExceptionManagement/DataAccess/Oracle/RetrieveExceptionList.process</processName>
            <processNameXPath>concat("/ExceptionManagement/DataAccess/",$_globalVariables/ns4:GlobalVariables/Database/MIG_DatabaseType,"/RetrieveExceptionList.process")</processNameXPath>
        </config>
        <pd:inputBindings>
            <xsl:copy-of select="$Start/wsdlPfx:ExceptionListQuery/parameters/ns5:ListQuery"/>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch Exception List Not Found">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>545</pd:x>
        <pd:y>62</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=DBRecordNotFound namespace=http://www.tibco.com/CommonLE2/namespace/private/Common</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Catch All Errors">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>50</pd:x>
        <pd:y>174</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <catchAll>true</catchAll>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Local Exception Handler">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>182</pd:x>
        <pd:y>179</pd:y>
        <config>
            <processName>/Common/Local Exception Handler.process</processName>
        </config>
        <pd:inputBindings>
            <ns12:Exception>
                <ErrorMessage>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </ErrorMessage>
                <ErrorCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </ErrorCode>
                <ns12:Error>
                    <xsl:for-each xmlns:xsl="http://www.w3.org/1999/XSL/Transform" select="$_error/ns:ErrorReport">
                        <ns12:ErrorReport>
                            <StackTrace>
                                <xsl:value-of select="StackTrace"/>
                            </StackTrace>
                            <Msg>
                                <xsl:value-of select="Msg"/>
                            </Msg>
                            <FullClass>
                                <xsl:value-of select="FullClass"/>
                            </FullClass>
                            <Class>
                                <xsl:value-of select="Class"/>
                            </Class>
                            <ProcessStack>
                                <xsl:value-of select="ProcessStack"/>
                            </ProcessStack>
                            <MsgCode>
                                <xsl:value-of select="MsgCode"/>
                            </MsgCode>
                        </ns12:ErrorReport>
                    </xsl:for-each>
                </ns12:Error>
            </ns12:Exception>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Generate Internal Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>312</pd:x>
        <pd:y>180</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch Too Many Records">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>51</pd:x>
        <pd:y>291</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=TooManyRecords namespace=http://www.tibco.com/CommonLE2/namespace/private/Common</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Generate Too Many Records Fault">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>272</pd:x>
        <pd:y>293</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$Catch-Too-Many-Records/pfx4:TooManyRecords/pfx4:Message"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$Catch-Too-Many-Records/pfx4:TooManyRecords/pfx4:Code"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$Catch-Too-Many-Records/pfx4:TooManyRecords/pfx4:Message"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$Catch-Too-Many-Records/pfx4:TooManyRecords/pfx4:Code"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>Retrieve Exception List</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Retrieve Exception List</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch All Errors</pd:from>
        <pd:to>Local Exception Handler</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Local Exception Handler</pd:from>
        <pd:to>Generate Internal Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch Too Many Records</pd:from>
        <pd:to>Generate Too Many Records Fault</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch Exception List Not Found</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>